import '@/design/index.scss';
import 'primevue/resources/primevue.min.css'; //core css
import 'primeicons/primeicons.css'; //icons
import 'primeflex/primeflex.css';

import PrimeVue from 'primevue/config';

import AutoComplete from 'primevue/autocomplete';
import Accordion from 'primevue/accordion';
import AccordionTab from 'primevue/accordiontab';
import Avatar from 'primevue/avatar';
import AvatarGroup from 'primevue/avatargroup';
import Badge from 'primevue/badge';
import BadgeDirective from 'primevue/badgedirective';
import BlockUI from 'primevue/blockui';
import Button from 'primevue/button';
import Breadcrumb from 'primevue/breadcrumb';
import Calendar from 'primevue/calendar';
import Card from 'primevue/card';
import CascadeSelect from 'primevue/cascadeselect';
import Carousel from 'primevue/carousel';
import Checkbox from 'primevue/checkbox';
import Chip from 'primevue/chip';
import Chips from 'primevue/chips';
import ColorPicker from 'primevue/colorpicker';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import ConfirmDialog from 'primevue/confirmdialog';
import ConfirmPopup from 'primevue/confirmpopup';
import ConfirmationService from 'primevue/confirmationservice';
import ContextMenu from 'primevue/contextmenu';
import DataTable from 'primevue/datatable';
import DataView from 'primevue/dataview';
import DataViewLayoutOptions from 'primevue/dataviewlayoutoptions';
import DeferredContent from 'primevue/deferredcontent';
import Dialog from 'primevue/dialog';
import DialogService from 'primevue/dialogservice';
import Divider from 'primevue/divider';
import Dock from 'primevue/dock';
import Dropdown from 'primevue/dropdown';
import DynamicDialog from 'primevue/dynamicdialog';
import Fieldset from 'primevue/fieldset';
import FileUpload from 'primevue/fileupload';
import FocusTrap from 'primevue/focustrap';
import Galleria from 'primevue/galleria';
import Image from 'primevue/image';
import InlineMessage from 'primevue/inlinemessage';
import Inplace from 'primevue/inplace';
import InputSwitch from 'primevue/inputswitch';
import InputText from 'primevue/inputtext';
import InputMask from 'primevue/inputmask';
import InputNumber from 'primevue/inputnumber';
import Knob from 'primevue/knob';
import Listbox from 'primevue/listbox';
import MegaMenu from 'primevue/megamenu';
import Menu from 'primevue/menu';
import Menubar from 'primevue/menubar';
import Message from 'primevue/message';
import MultiSelect from 'primevue/multiselect';
import OrderList from 'primevue/orderlist';
import OrganizationChart from 'primevue/organizationchart';
import OverlayPanel from 'primevue/overlaypanel';
import Paginator from 'primevue/paginator';
import Panel from 'primevue/panel';
import PanelMenu from 'primevue/panelmenu';
import Password from 'primevue/password';
import PickList from 'primevue/picklist';
import ProgressBar from 'primevue/progressbar';
import ProgressSpinner from 'primevue/progressspinner';
import Rating from 'primevue/rating';
import RadioButton from 'primevue/radiobutton';
import Ripple from 'primevue/ripple';
import Row from 'primevue/row';
import SelectButton from 'primevue/selectbutton';
import ScrollPanel from 'primevue/scrollpanel';
import ScrollTop from 'primevue/scrolltop';
import Skeleton from 'primevue/skeleton';
import Slider from 'primevue/slider';
import Sidebar from 'primevue/sidebar';
import SpeedDial from 'primevue/speeddial';
import SplitButton from 'primevue/splitbutton';
import Splitter from 'primevue/splitter';
import SplitterPanel from 'primevue/splitterpanel';
import Steps from 'primevue/steps';
import StyleClass from 'primevue/styleclass';
import TabMenu from 'primevue/tabmenu';
import TieredMenu from 'primevue/tieredmenu';
import Textarea from 'primevue/textarea';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
import Toolbar from 'primevue/toolbar';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import Tag from 'primevue/tag';
import Terminal from 'primevue/terminal';
import Timeline from 'primevue/timeline';
import ToggleButton from 'primevue/togglebutton';
import Tooltip from 'primevue/tooltip';
import Tree from 'primevue/tree';
import TreeSelect from 'primevue/treeselect';
import TreeTable from 'primevue/treetable';
import TriStateCheckbox from 'primevue/tristatecheckbox';
import VirtualScroller from 'primevue/virtualscroller';

export const usePrimeVue = (app) => {
    app.use(PrimeVue, { ripple: true });

    app.use(ToastService);
    app.use(ConfirmationService);
    app.use(DialogService);

    app.directive('tooltip', Tooltip);
    app.directive('badge', BadgeDirective);
    app.directive('ripple', Ripple);
    app.directive('styleclass', StyleClass);
    app.directive('focustrap', FocusTrap);

    app.component('p-accordion', Accordion);
    app.component('p-accordionTab', AccordionTab);
    app.component('p-autoComplete', AutoComplete);
    app.component('p-avatar', Avatar);
    app.component('p-avatarGroup', AvatarGroup);
    app.component('p-badge', Badge);
    app.component('p-blockUI', BlockUI);
    app.component('p-breadcrumb', Breadcrumb);
    app.component('p-button', Button);
    app.component('p-calendar', Calendar);
    app.component('p-card', Card);
    app.component('p-carousel', Carousel);
    app.component('p-cascadeSelect', CascadeSelect);
    app.component('p-checkbox', Checkbox);
    app.component('p-chip', Chip);
    app.component('p-chips', Chips);
    app.component('p-colorPicker', ColorPicker);
    app.component('p-column', Column);
    app.component('p-columnGroup', ColumnGroup);
    app.component('p-confirmDialog', ConfirmDialog);
    app.component('p-confirmPopup', ConfirmPopup);
    app.component('p-contextMenu', ContextMenu);
    app.component('p-dataTable', DataTable);
    app.component('p-dataView', DataView);
    app.component('p-dataViewLayoutOptions', DataViewLayoutOptions);
    app.component('p-deferredContent', DeferredContent);
    app.component('p-dialog', Dialog);
    app.component('p-divider', Divider);
    app.component('p-dock', Dock);
    app.component('p-dropdown', Dropdown);
    app.component('p-dynamicDialog', DynamicDialog);
    app.component('p-fieldset', Fieldset);
    app.component('p-fileUpload', FileUpload);
    app.component('p-galleria', Galleria);
    app.component('p-image', Image);
    app.component('p-inlineMessage', InlineMessage);
    app.component('p-inplace', Inplace);
    app.component('p-inputMask', InputMask);
    app.component('p-inputNumber', InputNumber);
    app.component('p-inputSwitch', InputSwitch);
    app.component('p-inputText', InputText);
    app.component('p-knob', Knob);
    app.component('p-listbox', Listbox);
    app.component('p-megaMenu', MegaMenu);
    app.component('p-menu', Menu);
    app.component('p-menubar', Menubar);
    app.component('p-message', Message);
    app.component('p-multiSelect', MultiSelect);
    app.component('p-orderList', OrderList);
    app.component('p-organizationChart', OrganizationChart);
    app.component('p-overlayPanel', OverlayPanel);
    app.component('p-paginator', Paginator);
    app.component('p-panel', Panel);
    app.component('p-panelMenu', PanelMenu);
    app.component('p-password', Password);
    app.component('p-pickList', PickList);
    app.component('p-progressBar', ProgressBar);
    app.component('p-progressSpinner', ProgressSpinner);
    app.component('p-radioButton', RadioButton);
    app.component('p-rating', Rating);
    app.component('p-row', Row);
    app.component('p-selectButton', SelectButton);
    app.component('p-scrollPanel', ScrollPanel);
    app.component('p-scrollTop', ScrollTop);
    app.component('p-slider', Slider);
    app.component('p-sidebar', Sidebar);
    app.component('p-skeleton', Skeleton);
    app.component('p-speedDial', SpeedDial);
    app.component('p-splitButton', SplitButton);
    app.component('p-splitter', Splitter);
    app.component('p-splitterPanel', SplitterPanel);
    app.component('p-steps', Steps);
    app.component('p-tabMenu', TabMenu);
    app.component('p-tabView', TabView);
    app.component('p-tabPanel', TabPanel);
    app.component('p-tag', Tag);
    app.component('p-textarea', Textarea);
    app.component('p-terminal', Terminal);
    app.component('p-tieredMenu', TieredMenu);
    app.component('p-timeline', Timeline);
    app.component('p-toast', Toast);
    app.component('p-toolbar', Toolbar);
    app.component('p-toggleButton', ToggleButton);
    app.component('p-tree', Tree);
    app.component('p-treeSelect', TreeSelect);
    app.component('p-treeTable', TreeTable);
    app.component('p-triStateCheckbox', TriStateCheckbox);
    app.component('p-virtualScroller', VirtualScroller);
};