export const CLASS_CONSTANTS = {
  feca: 'feca',
  osamodas: 'osamodas',
  enutrof: 'enutrof',
  sram: 'sram',
  xelor: 'xelor',
  ecaflip: 'ecaflip',
  eniripsa: 'eniripsa',
  iop: 'iop',
  cra: 'cra',
  sadida: 'sadida',
  sacrier: 'sacrier',
  pandawa: 'pandawa',
  rogue: 'rogue',
  masqueraider: 'masqueraider',
  ouginak: 'ouginak',
  foggernaut: 'foggernaut',
  eliotrope: 'eliotrope',
  huppermage: 'huppermage',
};

export const ITEM_SLOT_DATA = {
  HEAD: { id: 'HEAD', name: 'Helmet' },
  CHEST: { id: 'CHEST', name: 'Breastplace' },
  SHOULDERS: { id: 'SHOULDERS', name: 'Epaulettes' },
  LEGS: { id: 'LEGS', name: 'Boots' },
  NECK: { id: 'NECK', name: 'Amulet' },
  BACK: { id: 'BACK', name: 'Cloak' },
  BELT: { id: 'BELT', name: 'Belt' },
  FIRST_WEAPON: { id: 'FIRST_WEAPON', name: 'Primary Weapon' },
  SECOND_WEAPON: { id: 'SECOND_WEAPON', name: 'Secondary Weapon' },
  LEFT_HAND: { id: 'LEFT_HAND', name: 'Left Ring' },
  RIGHT_HAND: { id: 'RIGHT_HAND', name: 'Right Ring' },
  ACCESSORY: { id: 'ACCESSORY', name: 'Emblem' },
};
